# Generated by Django 6.0.3 on 2026-05-06 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_notificatio_recipie_684eac_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='action_label',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='notification',
            name='action_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='notification',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('system', 'System'), ('account', 'Account'), ('project', 'Project'), ('proposal', 'Proposal'), ('application', 'Application'), ('invitation', 'Invitation'), ('workflow', 'Workflow'), ('task', 'Task'), ('withdrawal', 'Withdrawal')], default='system', max_length=30),
        ),
        migrations.AddField(
            model_name='notification',
            name='entity_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='entity_type',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='notification',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10),
        ),
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('system_notice', 'System Notice'), ('account_created', 'Account Created'), ('account_imported', 'Account Imported'), ('password_changed', 'Password Changed'), ('hod_assigned', 'HoD Assigned'), ('idea_submitted', 'Idea Submitted'), ('idea_approved', 'Idea Approved'), ('idea_rejected', 'Idea Rejected'), ('proposal_submitted', 'Proposal Submitted'), ('proposal_approved_sup', 'Proposal Approved by Supervisor'), ('proposal_approved_hod', 'Proposal Approved by HoD'), ('proposal_rejected', 'Proposal Rejected'), ('proposal_assigned', 'Proposal Assigned'), ('application_submitted', 'Application Submitted'), ('application_approved_doc', 'Application Approved by Doctor'), ('application_approved_hod', 'Application Approved by HoD'), ('application_rejected', 'Application Rejected'), ('application_registered', 'Application Registered'), ('invitation_received', 'Invitation Received'), ('invitation_accepted', 'Invitation Accepted'), ('invitation_rejected', 'Invitation Rejected'), ('withdrawal_requested', 'Withdrawal Requested'), ('withdrawal_approved', 'Withdrawal Approved'), ('withdrawal_rejected', 'Withdrawal Rejected'), ('task_created', 'Task Created'), ('task_assigned', 'Task Assigned'), ('task_updated', 'Task Updated'), ('task_completed', 'Task Completed'), ('task_comment_added', 'Task Comment Added'), ('task_attachment_added', 'Task Attachment Added'), ('workflow_applied', 'Workflow Applied'), ('workflow_stage_submitted', 'Workflow Stage Submitted'), ('workflow_stage_approved', 'Workflow Stage Approved'), ('workflow_stage_rejected', 'Workflow Stage Rejected'), ('workflow_due_soon', 'Workflow Due Soon')], max_length=80),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'archived_at', '-created_at'], name='notificatio_recipie_c23041_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'category', 'is_read'], name='notificatio_recipie_130037_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'priority', 'is_read'], name='notificatio_recipie_299942_idx'),
        ),
    ]
