# Generated by Django 6.0.3 on 2026-05-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_ideaapplication_projects_id_student_09f121_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentideaproposal',
            name='team_size_reason',
            field=models.TextField(blank=True, help_text='Required when team_size is 1 or 4'),
        ),
    ]
