# Generated by Django 6.0.3 on 2026-05-06 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_alter_studentideaproposal_team_size_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectWithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to='projects.ideaapplication')),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to='projects.studentideaproposal')),
                ('reviewed_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'hod'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_project_withdrawals', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='project_withdrawal_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['student', 'status', '-created_at'], name='projects_pr_student_9a99df_idx'), models.Index(fields=['status', '-created_at'], name='projects_pr_status_a671a8_idx'), models.Index(fields=['proposal', 'status'], name='projects_pr_proposa_686742_idx'), models.Index(fields=['application', 'status'], name='projects_pr_applica_35babe_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('application__isnull', True), ('proposal__isnull', False)), models.Q(('application__isnull', False), ('proposal__isnull', True)), _connector='OR'), name='withdrawal_links_exactly_one_project'), models.UniqueConstraint(condition=models.Q(('proposal__isnull', False), ('status', 'pending')), fields=('student', 'proposal'), name='unique_pending_withdrawal_per_proposal_member'), models.UniqueConstraint(condition=models.Q(('application__isnull', False), ('status', 'pending')), fields=('student', 'application'), name='unique_pending_withdrawal_per_application_member')],
            },
        ),
    ]
