# Generated by Django 6.0.3 on 2026-05-08 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_projectwithdrawalrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentideaproposal',
            name='supervisor_count',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='ProposalSupervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_assignments', to='projects.studentideaproposal')),
                ('supervisor', models.ForeignKey(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='proposal_supervisor_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['supervisor', 'status'], name='projects_pr_supervi_d89a69_idx'), models.Index(fields=['proposal', 'status'], name='projects_pr_proposa_78125b_idx')],
                'unique_together': {('proposal', 'supervisor')},
            },
        ),
    ]
