# Generated by Django 6.0.3 on 2026-05-05 18:16

import workflow.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_workflow_indexes_active_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowfieldresponse',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=workflow.models._workflow_response_upload_path),
        ),
        migrations.AddField(
            model_name='workflowfieldresponse',
            name='file_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workflowfieldresponse',
            name='filename',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
